packageExtensions:
  "@apollo/client@*":
    dependencies:
      process: "*"
  next@*:
    dependencies:
      querystring: "*"
  ts-invariant@*:
    dependencies:
      process: "*"

# yarnPath: .yarn/releases/yarn-3.1.1.cjs
