yarnPath: ".yarn/releases/yarn-berry.js"
packageExtensions:
    "@apollo/client@*":
        dependencies:
            "process": "*"
    "@material-ui/pickers@*":
        dependencies:
            "date-fns": "*"
            "@babel/runtime": "*"
    "next@*":
        dependencies:
            "querystring": "*"
            "caniuse-lite": "*"
    "ts-invariant@*":
        dependencies:
            "process": "*"