yarnPath: ".yarn/releases/yarn-berry.js"
packageExtensions:
    "@apollo/link-context@*":
        dependencies:
            "graphql": "^14.5.4"
    "@apollo/react-common@*":
        dependencies:
            "graphql": "^14.5.4"
    "@apollo/client@*":
        dependencies:
            "react": "*"
    "jss-plugin-rule-value-function@*":
        dependencies:
            "tiny-warning": "*"
    "next@*":
        dependencies:
            "schema-utils": "*"
