yarnPath: ".yarn/releases/yarn-sources.cjs"
packageExtensions:
    "@apollo/client@*":
        dependencies:
            "process": "*"
    "next@*":
        dependencies:
            "querystring": "*"
    "ts-invariant@*":
        dependencies:
            "process": "*"